# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.box = "alpine/alpine64"
  config.vm.hostname = 'astaire64'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = "8192"
    vb.cpus = 4
    vb.name = "astaire"
  end

  config.vm.provision :shell, :path => ""
end
